server:
  port: 8080
  context-path: /test
logging:
  level: 
    com.play.phedb.dao.mapper: DEBUG  
spring: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:  
    name: mydb  
    #type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://127.0.0.1:3306/phedb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: wjuser  
    password: wjbasepwd 
   # driver-class-name: com.mysql.jdbc.Driver  
   # minIdle: 1  
    #maxActive: 2  
    #initialSize: 1  
    #timeBetweenEvictionRunsMillis: 3000  
   # minEvictableIdleTimeMillis: 300000  
   # validationQuery: SELECT 'ZTM' FROM DUAL  
   # testWhileIdle: true  
   # testOnBorrow: false  
   # testOnReturn: false
mybatis:   
  mapperLocations: classpath*:com/play/phedb/dao/mapper/xml/*.xml  
